# Biome Groupings ######################################################################################################

BIOMES = {
    "arid": [
        "biomesoplenty:lush_desert",
        "biomesoplenty:outback",
        "biomesoplenty:xeric_shrubland",
        "minecraft:savanna",
        "minecraft:savanna_rock",
    ],
    "cold_desert": [
        "biomesoplenty:cold_desert",
        "biomesoplenty:steppe",
        "biomesoplenty:tundra",
        "minecraft:ice_flats",
        "minecraft:taiga_cold",
        "minecraft:taiga_cold_hills",
    ],
    "cold_forest": [
        "biomesoplenty:boreal_forest",
        "biomesoplenty:coniferous_forest",
        "biomesoplenty:maple_woods",
        "biomesoplenty:seasonal_forest",
        "biomesoplenty:shield",
        "biomesoplenty:snowy_coniferous_forest",
        "biomesoplenty:snowy_forest",
        "minecraft:redwood_taiga",
        "minecraft:redwood_taiga_hills",
        "minecraft:taiga",
        "minecraft:taiga_hills",
    ],
    "desert": [
        "minecraft:desert",
        "minecraft:desert_hills",
        "minecraft:mutated_desert",
    ],
    "end": [
        "minecraft:sky",
    ],
    "frozen": [
        "biomesoplenty:glacier",
    ],
    "hills": [
        "biomesoplenty:alps_foothills",
        "biomesoplenty:chaparral",
        "biomesoplenty:moor",
        "biomesoplenty:mountain_foothills",
        "minecraft:extreme_hills",
        "minecraft:extreme_hills_with_trees",
        "minecraft:mushroom_island",
        "minecraft:mutated_extreme_hills",
        "minecraft:smaller_extreme_hills",
    ],
    "mesa": [
        "minecraft:mesa",
        "minecraft:mesa_rock",
        "minecraft:mesa_clear_rock",
    ],
    "mountains": [
        "biomesoplenty:alps",
        "biomesoplenty:crag",
        "biomesoplenty:highland",
        "biomesoplenty:mountain",
        "biomesoplenty:overgrown_cliffs",
        "biomesoplenty:volcanic_island",
        "minecraft:ice_mountains",
    ],
    "nether": [
        "biomesoplenty:corrupted_sands",
        "biomesoplenty:phantasmagoric_inferno",
        "biomesoplenty:undergarden",
        "biomesoplenty:visceral_heap",
        "minecraft:hell",
    ],
    "ocean": [
        "biomesoplenty:coral_reef",
        "biomesoplenty:kelp_forest",
        "minecraft:deep_ocean",
        "minecraft:ocean",
        "minecraft:frozen_ocean",
    ],
    "plains": [
        "biomesoplenty:brushland",
        "biomesoplenty:flower_field",
        "biomesoplenty:flower_island",
        "biomesoplenty:grassland",
        "biomesoplenty:lavender_fields",
        "biomesoplenty:meadow",
        "biomesoplenty:origin_island",
        "biomesoplenty:pasture",
        "biomesoplenty:prairie",
        "biomesoplenty:shrubland",
        "minecraft:mutated_plains",
        "minecraft:plains",
    ],
    "shore": [
        "biomesoplenty:gravel_beach",
        "biomesoplenty:origin_beach",
        "biomesoplenty:white_beach",
        "minecraft:beaches",
        "minecraft:cold_beach",
        "minecraft:frozen_river",
        "minecraft:mushroom_island_shore",
        "minecraft:river",
        "minecraft:stone_beach",
    ],
    "swamp": [
        "biomesoplenty:bayou",
        "biomesoplenty:bog",
        "biomesoplenty:fen",
        "biomesoplenty:land_of_lakes",
        "biomesoplenty:lush_swamp",
        "biomesoplenty:mangrove",
        "biomesoplenty:marsh",
        "biomesoplenty:wetland",
        "minecraft:swampland",
    ],
    "temperate_forest": [
        "biomesoplenty:cherry_blossom_grove",
        "biomesoplenty:fungi_forest",
        "biomesoplenty:grove",
        "biomesoplenty:mystic_grove",
        "biomesoplenty:ominous_woods",
        "biomesoplenty:orchard",
        "biomesoplenty:redwood_forest",
        "biomesoplenty:woodland",
        "minecraft:birch_forest",
        "minecraft:birch_forest_hills",
        "minecraft:forest",
        "minecraft:forest_hills",
        "minecraft:mutated_forest",
        "minecraft:roofed_forest",
    ],
    "tropical": [
        "biomesoplenty:oasis",
        "biomesoplenty:rainforest",
        "biomesoplenty:temperate_rainforest",
        "biomesoplenty:tropical_island",
        "biomesoplenty:tropical_rainforest",
        "minecraft:jungle",
        "minecraft:jungle_edge",
        "minecraft:jungle_hills",
    ],
    "warm_forest": [
        "biomesoplenty:bamboo_forest",
        "biomesoplenty:eucalyptus_forest",
        "biomesoplenty:sacred_springs",
    ],
    "wasteland": [
        "biomesoplenty:dead_forest",
        "biomesoplenty:dead_swamp",
        "biomesoplenty:quagmire",
        "biomesoplenty:wasteland",
    ],
}

overworld = "arid cold_desert cold_forest desert frozen hills mesa mountains ocean plains shore swamp " \
    "temperate_forest warm_forest wasteland"
BIOMES["overworld"] = []
for name in overworld.split(" "):
    for biome in BIOMES[name]:
        BIOMES["overworld"].append(biome)
